export const NUMBER_FACT_REQUEST = 'NUMBER_FACT_REQUEST';
export const NUMBER_FACT_RECEIVE = 'NUMBER_FACT_RECEIVE';
export const NUMBER_FACT_ERROR = 'NUMBER_FACT_ERROR';
export const NUMBER_COUNTER_ADD = 'NUMBER_COUNTER_ADD';

export const TAP_REQUEST = 'TAP_REQUEST';
export const TAP_RECEIVE = 'TAP_RECEIVE';
export const TAP_ERROR = 'TAP_ERROR';

export const DELETE_TAPS_REQUEST = 'DELETE_TAPS_REQUEST';
export const DELETE_TAPS_RECEIVE = 'DELETE_TAPS_RECEIVE';
export const DELETE_TAPS_ERROR = 'DELETE_TAPS_ERROR';
